#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

#define MUGSHOT_NONE  0
#define MUGSHOT_TEST  1
#define MUGSHOT_ISABELL 2
#define MUGSHOT_DANIA 3
#define MUGSHOT_CECILE 4
#define MUGSHOT_ISARIA 5
#define MUGSHOT_COUNT 6

#define EMOTE_NORMAL  0
#define EMOTE_ALT     1
#define EMOTE_COUNT   2

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
