Whitecliff_Castle_House2_MapScripts::
	.byte 0


Whitecliff_House2_Man::
# 6 "data/maps/Whitecliff_Castle_House2/scripts.pory"
	msgbox Whitecliff_House2_Man_Chat, MSGBOX_NPC
	return


Whitecliff_House2_Man_Chat::
# 9 "data/maps/Whitecliff_Castle_House2/scripts.pory"
	.string "Don't mind my old man outside. He's\n getting old and senile.\pThe sun moves, can you believe it?\n What's next, the sky is red?$"
