Common_Eventscript_Inn_Heal::
# 2 "data/scripts/gthcscripts/global_scripts.pory"
	fadescreen FADE_TO_BLACK
# 3 "data/scripts/gthcscripts/global_scripts.pory"
	special HealPlayerParty
# 4 "data/scripts/gthcscripts/global_scripts.pory"
	playfanfare MUS_HEAL
# 5 "data/scripts/gthcscripts/global_scripts.pory"
	delay 80
# 6 "data/scripts/gthcscripts/global_scripts.pory"
	fadescreen FADE_FROM_BLACK
	return

